centos-kvm.sh
khairilg/script-jualan-ssh-vpn pull request #1
Opened 2018-07-12 12:44 UTC by BangSalman

2019-07-08 09:08 UTC, ipaypeak commented
halo ini kenapa saya buat user baru malah gamau konek ya? kalo pakai user default dan user trial bisa. ada solusi?

2019-07-09 18:28 UTC, Sh4rkD1ck commented
Itu script lama gan

Pada tanggal Sen, 8 Jul 2019 16.08, ipaypeak <notifications@github.com>
menulis:

> halo ini kenapa saya buat user baru malah gamau konek ya? kalo pakai user
> default dan user trial bisa. ada solusi?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/khairilg/script-jualan-ssh-vpn/pull/1?email_source=notifications&email_token=AIAOIYGSZYS3UQT7QHNDXV3P6L7XLA5CNFSM4FJTD2E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZMO2MA#issuecomment-509144368>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIAOIYDWXRTZ5SKDA3HERNLP6L7XLANCNFSM4FJTD2EQ>
> .
>

2019-07-11 11:33 UTC, ipaypeak commented
Ada update skrip barunya ga? Hehe

Pada tanggal Rab, 10 Jul 2019 01.28, bang-salman <notifications@github.com>
menulis:

> Itu script lama gan
>
> Pada tanggal Sen, 8 Jul 2019 16.08, ipaypeak <notifications@github.com>
> menulis:
>
> > halo ini kenapa saya buat user baru malah gamau konek ya? kalo pakai user
> > default dan user trial bisa. ada solusi?
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/khairilg/script-jualan-ssh-vpn/pull/1?email_source=notifications&email_token=AIAOIYGSZYS3UQT7QHNDXV3P6L7XLA5CNFSM4FJTD2E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZMO2MA#issuecomment-509144368
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe-auth/AIAOIYDWXRTZ5SKDA3HERNLP6L7XLANCNFSM4FJTD2EQ
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/khairilg/script-jualan-ssh-vpn/pull/1?email_source=notifications&email_token=AIX6ROPLPAKCYMQJWKFIK3TP6TKE5A5CNFSM4FJTD2E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZRDZQY#issuecomment-509754563>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIX6ROO3KAWWI3JSG7ZOPMTP6TKE5ANCNFSM4FJTD2EQ>
> .
>

2019-07-14 11:38 UTC, Sh4rkD1ck commented
ditunggu aja ya gan

Pada tanggal Kam, 11 Jul 2019 18.33, ipaypeak <notifications@github.com>
menulis:

> Ada update skrip barunya ga? Hehe
>
> Pada tanggal Rab, 10 Jul 2019 01.28, bang-salman <notifications@github.com
> >
> menulis:
>
> > Itu script lama gan
> >
> > Pada tanggal Sen, 8 Jul 2019 16.08, ipaypeak <notifications@github.com>
> > menulis:
> >
> > > halo ini kenapa saya buat user baru malah gamau konek ya? kalo pakai
> user
> > > default dan user trial bisa. ada solusi?
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/khairilg/script-jualan-ssh-vpn/pull/1?email_source=notifications&email_token=AIAOIYGSZYS3UQT7QHNDXV3P6L7XLA5CNFSM4FJTD2E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZMO2MA#issuecomment-509144368
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/AIAOIYDWXRTZ5SKDA3HERNLP6L7XLANCNFSM4FJTD2EQ
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/khairilg/script-jualan-ssh-vpn/pull/1?email_source=notifications&email_token=AIX6ROPLPAKCYMQJWKFIK3TP6TKE5A5CNFSM4FJTD2E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZRDZQY#issuecomment-509754563
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe-auth/AIX6ROO3KAWWI3JSG7ZOPMTP6TKE5ANCNFSM4FJTD2EQ
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/khairilg/script-jualan-ssh-vpn/pull/1?email_source=notifications&email_token=AIAOIYAVJTUE7HUH7UTGIPDP64LCFA5CNFSM4FJTD2E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZWNIFY#issuecomment-510448663>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIAOIYDREKNEUDYWAON4H7DP64LCFANCNFSM4FJTD2EQ>
> .
>

2020-12-05 05:09 UTC, khairilg requested changes
Maaf untuk port sepertinya belum perlu untuk diganti jika tidak ada konflik. Untuk penggunaan port kostum bisa fork script ini lalu edit. #1

2020-12-05 05:09 UTC, closed without merging